# This file was generated by GoReleaser. DO NOT EDIT.
cask "steno" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "80fcd5d305afbe6b1b054a0b09433cb7a4830c03023ffe4ebf2a55c923dd2e9a"
      url "https://github.com/sur1cat/steno/releases/download/v#{version}/steno_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5db96c4d536a1eb751f8884b27c222b79742a601a53e490b0e069b397ac1e4d8"
      url "https://github.com/sur1cat/steno/releases/download/v#{version}/steno_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5289859d1f2fc6a881cfd4025a7f0969f3b5112bc8164aa57196faa4152f7d5c"
      url "https://github.com/sur1cat/steno/releases/download/v#{version}/steno_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e08837fc80abecf7cb57d672f2d1d23b785f6adafb74e096703e6e8f40ad1e6b"
      url "https://github.com/sur1cat/steno/releases/download/v#{version}/steno_#{version}_linux_amd64.tar.gz"
    end
  end

  name "steno"
  desc "Meeting notes and follow-ups: a bot joins your calls, records, transcribes, publishes"
  homepage "https://github.com/sur1cat/steno"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
    ]

  binary "steno"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/steno"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Настройка одной командой — она спросит всё нужное и проверит по ходу:

      steno setup

    Боту нужен контейнер с Chromium, PulseAudio и ffmpeg:

      git clone https://github.com/sur1cat/steno && cd steno && make bot-image

    Для распознавания на своей машине (не нужно с Groq и с субтитрами):

      brew install whisper-cpp jq
  EOS
end
