# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pitwall < Formula
  desc "The instrument panel for a fleet of coding agents"
  homepage "https://github.com/sur1cat/pitwall"
  version "0.13.0"
  license "MIT"

  depends_on "git" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sur1cat/pitwall/releases/download/v0.13.0/pitwall_0.13.0_darwin_amd64.tar.gz"
      sha256 "1beae9c5fd58c76bd5f3641ba44b806dad22444bbcce757a3f8ea57106aa21ab"

      define_method(:install) do
        bin.install "pitwall"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sur1cat/pitwall/releases/download/v0.13.0/pitwall_0.13.0_darwin_arm64.tar.gz"
      sha256 "c149deb0759cc9ef41d220b617da844c5fc07932481f2e49cb8996aea458b3cc"

      define_method(:install) do
        bin.install "pitwall"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sur1cat/pitwall/releases/download/v0.13.0/pitwall_0.13.0_linux_amd64.tar.gz"
      sha256 "edcad20ad61aa0a0b8e57dea376e7051a703d43699140a3fffe493bac149304a"
      define_method(:install) do
        bin.install "pitwall"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sur1cat/pitwall/releases/download/v0.13.0/pitwall_0.13.0_linux_arm64.tar.gz"
      sha256 "b6cb70b70f79cc7539d29c633d97f34f291b3b2f51291813d0f17c9647d06316"
      define_method(:install) do
        bin.install "pitwall"
      end
    end
  end

  def caveats
    <<~EOS
      pitwall reads what Claude Code already wrote to disk. Start with:

        pitwall            one screen: who is working, what today cost
        pitwall perms      which permission rules can never match
        pitwall install    add a status line to Claude Code

      The macOS menu bar app is not installed by this formula. Build it with:

        git clone https://github.com/sur1cat/pitwall && cd pitwall/bar && ./build.sh
    EOS
  end

  test do
    assert_match "pitwall", shell_output("#{bin}/pitwall version")
  end
end
