# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pitwall < Formula
  desc "The instrument panel for a fleet of coding agents"
  homepage "https://github.com/sur1cat/pitwall"
  version "0.2.0"
  license "MIT"

  depends_on "git" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sur1cat/pitwall/releases/download/v0.2.0/pitwall_0.2.0_darwin_amd64.tar.gz"
      sha256 "9c971cb3f929c76064576dcc1230772558adf4d667b6fbacc855068746ac81b3"

      define_method(:install) do
        bin.install "pitwall"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sur1cat/pitwall/releases/download/v0.2.0/pitwall_0.2.0_darwin_arm64.tar.gz"
      sha256 "76107e8a8671d1b2e1c4ad303552c1c4efc5e94817a8edb9a3438f630cc11fed"

      define_method(:install) do
        bin.install "pitwall"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sur1cat/pitwall/releases/download/v0.2.0/pitwall_0.2.0_linux_amd64.tar.gz"
      sha256 "edb80831d2ec1f94b6532c7f966448da7c321196040ac77269b0ebc0b3852b3d"
      define_method(:install) do
        bin.install "pitwall"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sur1cat/pitwall/releases/download/v0.2.0/pitwall_0.2.0_linux_arm64.tar.gz"
      sha256 "f3777dd91676818e23f42786a79657832f1e1f039db1ad75cd07fd326aa3945d"
      define_method(:install) do
        bin.install "pitwall"
      end
    end
  end

  def caveats
    <<~EOS
      pitwall reads what Claude Code already wrote to disk. Start with:

        pitwall            one screen: who is working, what today cost
        pitwall perms      which permission rules can never match
        pitwall install    add a status line to Claude Code

      The macOS menu bar app is not installed by this formula. Build it with:

        git clone https://github.com/sur1cat/pitwall && cd pitwall/bar && ./build.sh
    EOS
  end

  test do
    assert_match "pitwall", shell_output("#{bin}/pitwall version")
  end
end
