# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pitwall < Formula
  desc "The instrument panel for a fleet of coding agents"
  homepage "https://github.com/sur1cat/pitwall"
  version "0.9.0"
  license "MIT"

  depends_on "git" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sur1cat/pitwall/releases/download/v0.9.0/pitwall_0.9.0_darwin_amd64.tar.gz"
      sha256 "604fede306f094b3b1d97b225aa0130b72f41c381614a4041b181f3860326720"

      define_method(:install) do
        bin.install "pitwall"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sur1cat/pitwall/releases/download/v0.9.0/pitwall_0.9.0_darwin_arm64.tar.gz"
      sha256 "b8256f72a8fef35f7f3a4cd6e94ca0a123a985ad936db74604244a863131e316"

      define_method(:install) do
        bin.install "pitwall"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sur1cat/pitwall/releases/download/v0.9.0/pitwall_0.9.0_linux_amd64.tar.gz"
      sha256 "a1d9b9b3c91ad73a383e43e750cc38be00fb0444d40654a5efe13ac2a76f49d5"
      define_method(:install) do
        bin.install "pitwall"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sur1cat/pitwall/releases/download/v0.9.0/pitwall_0.9.0_linux_arm64.tar.gz"
      sha256 "d7804be3ca7e9e6aee209e002896ac1cd2693388bb3ebb1fee4991d74cad9864"
      define_method(:install) do
        bin.install "pitwall"
      end
    end
  end

  def caveats
    <<~EOS
      pitwall reads what Claude Code already wrote to disk. Start with:

        pitwall            one screen: who is working, what today cost
        pitwall perms      which permission rules can never match
        pitwall install    add a status line to Claude Code

      The macOS menu bar app is not installed by this formula. Build it with:

        git clone https://github.com/sur1cat/pitwall && cd pitwall/bar && ./build.sh
    EOS
  end

  test do
    assert_match "pitwall", shell_output("#{bin}/pitwall version")
  end
end
