# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Steno < Formula
  desc "Meeting notes and follow-ups: a bot joins your calls, records, transcribes, publishes"
  homepage "https://github.com/sur1cat/steno"
  version "0.3.0"
  license "MIT"

  depends_on "ffmpeg"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sur1cat/steno/releases/download/v0.3.0/steno_0.3.0_darwin_amd64.tar.gz"
      sha256 "c97d488965db8919f11b67b9964e72367ba28fca4de0f671ba46e767cd6459d8"

      define_method(:install) do
        bin.install "steno"
        pkgshare.install "adapters"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sur1cat/steno/releases/download/v0.3.0/steno_0.3.0_darwin_arm64.tar.gz"
      sha256 "60acc141ccae250c04844b8cdb44e2ad944e7b6a9ac0712210e5cac8c00b8138"

      define_method(:install) do
        bin.install "steno"
        pkgshare.install "adapters"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sur1cat/steno/releases/download/v0.3.0/steno_0.3.0_linux_amd64.tar.gz"
      sha256 "ea056c19b8950189b8c79002985d3c2f8f2e3a312b2a03d8c6813b1002e9b75c"
      define_method(:install) do
        bin.install "steno"
        pkgshare.install "adapters"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sur1cat/steno/releases/download/v0.3.0/steno_0.3.0_linux_arm64.tar.gz"
      sha256 "9634a473ac87058e5ca46ffe27ae6727c77fd9f233242a357a4aa5c0c5f92404"
      define_method(:install) do
        bin.install "steno"
        pkgshare.install "adapters"
      end
    end
  end

  def caveats
    <<~EOS
      Настройка одной командой — она спросит всё нужное и проверит по ходу:

        steno setup

      Боту нужен Docker: контейнер с Chromium и звуком steno скачает сам перед
      первым созвоном. Заранее — docker pull ghcr.io/sur1cat/steno-bot

      Для распознавания на своей машине (не нужно с Groq и с субтитрами):

        brew install whisper-cpp jq
    EOS
  end

  test do
    assert_match "steno", shell_output("#{bin}/steno help")
    assert_predicate pkgshare/"adapters/whisper-cpp.sh", :exist?
  end
end
